### ISSUE TITLE
User experience bug.

### ISSUE THREAD

**Issue by devsyedmohsin** [gitpod-io/devx-community#101]
The text **developerexperience.us**  looks like a link although it is normal text. I was trying to follow the link but then realized it's a span element with some text. I would suggest to make it bold instead to show importance.

I can make a PR for this if you like.

![some normal text which looks like a link](https://user-images.githubusercontent.com/83846298/190429749-14e338a7-5e6e-4ebb-b544-2bb6f29f83af.png)

**Comment by nisarhassan12** [comment]
Hi, @devsyedmohsin Thanks for bringing this up. Feel free to raise a Pr for this.

**Comment by asmitbm** [comment]
Hey @Cahllagerfeld can I work on this as well?

**Comment by Cahllagerfeld** [comment]
Sure 👍
