### ISSUE TITLE
Add two new core members to the website

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/devx-community#110]
We have two new members join the core members team. I'll send you their details for the website CC @Cahllagerfeld

**Comment by pawlean** [comment]
❓ Does this affect the grid that we have now?

**Comment by Cahllagerfeld** [comment]
Yep, it will

**Comment by Cahllagerfeld** [comment]
Hey @chrifro, when adjusting the grid, I'd avoid horizontal scrolling. I'd suggest either using two rows with 5 icons, or leaving it as it is, and adding a third row with 2 more. What do you think?

**Comment by chrifro** [comment]
>leaving it as it is, and adding a third row with 2 more.

🎯 and let's align the two new ones to the center

**Comment by pawlean** [comment]
Hey @chrifro @Cahllagerfeld! Sorry about the delay with this. I still haven't received information about the second core member. Can we just put the single member for now?

**Comment by Cahllagerfeld** [comment]
The PR is open already, let me double check tomorrow, so we can ship it :) 🚢
