### ISSUE TITLE
Add top-level menu bar

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/devx-community#114]
Feedback from a potential community member:

> Quick feedback on https://www.developerexperience.us/ - when he scrolled through this it was a bit annoying that there is now top level menu bar that allows him to jump to the individual resources (feels more like dictate not integrate).

@chrifro Can we add links to the top for each section? WDYT design-wise?

**Comment by chrifro** [comment]
I added this style for the navigation bar
<img width="1439" alt="Bildschirmfoto 2022-11-15 um 14 31 38" src="https://user-images.githubusercontent.com/46345125/201932085-19ec0f1c-5dd7-42cf-9986-c48e7c484f64.png">

@pawlean could you specify which navigation items you'd like to have? So far I thought about these links
Devx -> "What is developer experience"
Community -> "What is community"
Resources -> "Learn more about developer experience" 

I don't think the founding members require a navigation item. WDYT?

**Regarding the implementation:**
- the nav bar should be fixed while scrolling, the bg has 80% opacity and 10px blur (similar to gitpod.io)
- on hover the navigation item turns black and bold

**Comment by pawlean** [comment]
These links and implementation is spot-on, @chrifro! 👾 Agreed with the founding members not being needed there!
