### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/devx-community#119]
Currently, it falls back to the netilfy 404 page. We should to have a custom 404 page in place. Thanks for the ping @Cahllagerfeld 🙏

See [mockup](https://www.figma.com/file/Xt5olSXad7hs5bQP9FF8Pl/DevX?node-id=758%3A379&t=hBMxLHmPwCUVfqmz-1)
<img width="711" alt="Bildschirmfoto 2022-12-12 um 10 56 29" src="https://user-images.githubusercontent.com/46345125/207016359-e98569d5-dd73-48d1-b76b-e217e8720e47.png">

**Comment by Cahllagerfeld** [comment]
closed with #120
