### ISSUE TITLE
Improve styles for clickable elements

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/devx-community#46]
- [x] align light/dark theme design with mockup [[1](https://www.figma.com/file/Xt5olSXad7hs5bQP9FF8Pl/DevX?node-id=116%3A951)]
<img width="144" alt="Bildschirmfoto 2022-09-05 um 08 05 48" src="https://user-images.githubusercontent.com/46345125/188371541-e329fbda-67af-4297-92ed-08a0fe9e0404.png">

- [x] adjust hover style: remove shadow only increase stroke size to 5px
- [x] set a fixed and even height for highlighted cards (see [mockup](https://www.figma.com/file/Xt5olSXad7hs5bQP9FF8Pl/DevX?node-id=2%3A384))
<img width="614" alt="Bildschirmfoto 2022-09-05 um 08 08 50" src="https://user-images.githubusercontent.com/46345125/188371933-1f011d27-1b8c-4da3-8388-c5497fd047d0.png">

- [x] highlighted cards should not move on hover
- [x] highlighted cards: text should not break on hover

**Comment by Cahllagerfeld** [comment]
Hey @chrifro, 
resolving the last two items here isn't that easy when changing the border width on hover. Changing the width, causes the browser to refloat the content inside them.
Do you have an idea to get around this @nisarhassan12?

**Comment by chrifro** [comment]
Did you see @jacobparis's suggestion? 
https://gitpod.slack.com/archives/C0401SXP0FP/p1662393633741769?thread_ts=1662389655.629079&cid=C0401SXP0FP

**Comment by Cahllagerfeld** [comment]
closing for now, as things are resolved / or included in followup issues
