### ISSUE TITLE
adjust spacing

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/devx-community#47]
- [ ] could we move the start screen (dots & headline) a bit further up? Currently it can easily be cut on smaller window sizes
- [x] reduce spacing (see [mockup](https://www.figma.com/file/Xt5olSXad7hs5bQP9FF8Pl/DevX?node-id=2%3A384))
<img width="917" alt="Bildschirmfoto 2022-09-05 um 08 16 46" src="https://user-images.githubusercontent.com/46345125/188372851-a4b238bb-5f4c-4d37-9de8-2334d4a903d2.png">

- [x] generally, align the spacing. I emphasized the spacing with red boxes next to the mockup
<img width="432" alt="Bildschirmfoto 2022-09-05 um 08 21 40" src="https://user-images.githubusercontent.com/46345125/188373573-389f4022-6897-4c85-93f9-6e4e625773c0.png">

- [x] reduce spacing for the founding members. 12px-8px (see mockup)
<img width="221" alt="Bildschirmfoto 2022-09-05 um 08 36 18" src="https://user-images.githubusercontent.com/46345125/188380778-e5ab8f65-a50c-47cb-8b45-c64ec97e5a2c.png">

**Comment by nisarhassan12** [comment]
>  could we move the start screen (dots & headline) a bit further up? Currently it can easily be cut on smaller window sizes

@chrifro we can't move the dots up unless we reduce the trajectory of the dots i.e at the start the top two dots are aligned at the very top right below the nav. Should I try changing the trajectory(I don't think that would look good)? 
![image](https://user-images.githubusercontent.com/46004116/188446732-b90c5780-1c13-47b9-bacb-f289baf9b8d4.png)

Alternatively, we could reduce the size of the dots more on mobile + also the spacing between the dots and the headline.  

I have fixed the rest in #60

**Comment by chrifro** [comment]
reducing this space from t0 48px would not work without changing the trajectory? We should keep the change as simple as possible
<img width="223" alt="Bildschirmfoto 2022-09-05 um 14 57 14" src="https://user-images.githubusercontent.com/46345125/188455203-6a7aff50-4d99-4ecb-8822-6b30838ead83.png">


If not, I like your suggestion of reducing the spacing between the dots and the headline, It could be around 48-56px

**Comment by nisarhassan12** [comment]
@chrifro I have made this Pr to adjust it as you suggested https://github.com/gitpod-io/devx-community/pull/67 Please have a look at the deploy preview and let me know if it needs further re-adjustments. Thanks
