### ISSUE TITLE
Improve animations

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/devx-community#48]
- [x] this section is not animated as one block
<img width="1015" alt="Bildschirmfoto 2022-09-05 um 08 31 24" src="https://user-images.githubusercontent.com/46345125/188377529-14b0516c-5e3c-49de-a9f3-af1aac5e4d5f.png">

- [ ] Could we reduce the slide-in distance for the text block slide-in animation? So shorting the movement? I think that will improve the snappiness as well [[1](https://gitpod.slack.com/archives/C0401SXP0FP/p1662100463325889)]

**Comment by nisarhassan12** [comment]
@chrifro For the animation I have addressed that in #58 I have decreased the distance to 100px from 200px. In my opinion, the animation with 200px looks better. What do you think?

**Comment by chrifro** [comment]
I like the new version a lot more. It's less intrusive. Are you fine with merging that?

**Comment by nisarhassan12** [comment]
Yeah sure. Let's do that.
