### ISSUE TITLE
mobile improvements

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/devx-community#51]
|production|mockup|
|-|-|
|<img width="385" alt="Bildschirmfoto 2022-09-05 um 09 15 40" src="https://user-images.githubusercontent.com/46345125/188389297-da55b01e-a31d-4a99-9c3e-f980022d2af8.png">|<img width="376" alt="Bildschirmfoto 2022-09-05 um 09 16 30" src="https://user-images.githubusercontent.com/46345125/188389655-867f3f78-43ad-4108-99bd-9838026f061e.png">|
|<img width="341" alt="Bildschirmfoto 2022-09-05 um 09 17 24" src="https://user-images.githubusercontent.com/46345125/188390207-b1b4072f-4011-4a67-b77c-95a17b1200a3.png">| <img width="229" alt="Bildschirmfoto 2022-09-05 um 09 18 16" src="https://user-images.githubusercontent.com/46345125/188390839-90cf4666-90f7-4195-ae21-edb361825861.png">|
|<img width="426" alt="Bildschirmfoto 2022-09-05 um 09 20 05" src="https://user-images.githubusercontent.com/46345125/188391228-43e44667-1e22-4490-b81a-ee687e9b547f.png">|<img width="213" alt="Bildschirmfoto 2022-09-05 um 09 20 41" src="https://user-images.githubusercontent.com/46345125/188391344-91ae769a-cfc0-4ca2-a2bf-6ccd729039f3.png">|
|<img width="423" alt="Bildschirmfoto 2022-09-05 um 09 21 47" src="https://user-images.githubusercontent.com/46345125/188391595-0b11a7a6-3b31-41b7-918f-467f20773cf5.png">|<img width="214" alt="Bildschirmfoto 2022-09-05 um 09 21 53" src="https://user-images.githubusercontent.com/46345125/188391641-40786ce8-2e94-444c-b6fd-cac70efac594.png">

**Comment by nisarhassan12** [comment]
Fixed in #73
