### ISSUE TITLE
general improvements

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/devx-community#72]
Now we are getting there. This is getting super nice! ✨ 

**A few more things I noticed:**

- [x] light/dark theme switch doesn't align with the mockup yet (no borders, remove system settings, grey on hover)
<img width="153" alt="Bildschirmfoto 2022-09-05 um 18 33 55" src="https://user-images.githubusercontent.com/46345125/188490292-de321a0e-1566-4273-8811-9d92c60dc6e8.png">

- [x] should be h4 (28px) instead of h5
<img width="626" alt="Bildschirmfoto 2022-09-05 um 18 36 20" src="https://user-images.githubusercontent.com/46345125/188490299-748ff7d7-1506-4ad5-9e8f-56c82fd07076.png">

- [x] looking at it now I think the spacing underneath the h2 headlines is too much. Could we change it from 64px to 48px?
- [x] the cards should have the same height and if possible be a square
<img width="612" alt="Bildschirmfoto 2022-09-05 um 18 39 54" src="https://user-images.githubusercontent.com/46345125/188490662-48ce94fa-ea03-4c03-a660-4a1b61fe4b82.png">

- [x] here the spacing is off (I guess it's still WIP)
<img width="666" alt="Bildschirmfoto 2022-09-05 um 18 40 38" src="https://user-images.githubusercontent.com/46345125/188490710-ad7da282-535d-4c82-a9bd-bdfcb1db9056.png">

- [x] the cards should have the same height in both rows
<img width="616" alt="Bildschirmfoto 2022-09-05 um 18 41 12" src="https://user-images.githubusercontent.com/46345125/188490787-49f5161c-9e3a-427e-af8d-4d9476417a88.png">

- [x] there might have been a misunderstanding about the button hover styles. It should be: no shadow & 5px stroke 
- [x] any reasoning why you used a wider column width than in the mockup? I think the spacing in the mockup looks less cramped
<img width="1027" alt="Bildschirmfoto 2022-09-05 um 18 44 31" src="https://user-images.githubusercontent.com/46345125/188491363-b1b39006-3d19-4345-84d1-5dd43a073e04.png">

- [x] title and company should be in 12px size (see mockup)
<img width="240" alt="Bildschirmfoto 2022-09-05 um 18 46 37" src="https://user-images.githubusercontent.com/46345125/188491348-c1cc1e64-6e1f-49dd-b1bf-2724252635af.png">

- [x] the footer alignment is off
<img width="1075" alt="Bildschirmfoto 2022-09-05 um 18 30 14" src="https://user-images.githubusercontent.com/46345125/188491419-bcd69ae6-eccb-4bc1-89a8-773daaab3425.png">

**Comment by pawlean** [comment]
Can you also add Elvis' last name: Kahroo? And move him to the bottom of the list?
