### ISSUE TITLE
Final review

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/devx-community#83]
I'm ignoring open issues like the missing dots, and the spacing for community recommendations

- [x] the hover effect for the CTA button is missing. It should have a 5px stroke on hover
- [x] hover effect for dark-light theme switcher
- [x] mobile: decrease the height for the highlighted cards. We don't need to leave so much space within the cards (not urgent)
<img width="492" alt="Bildschirmfoto 2022-09-06 um 16 10 51" src="https://user-images.githubusercontent.com/46345125/188657538-14ba2702-2e12-452f-ae02-882e129d3569.png">

- [x] mobile: increase width for bullet points
<img width="484" alt="Bildschirmfoto 2022-09-06 um 16 11 07" src="https://user-images.githubusercontent.com/46345125/188657746-ee1a7f63-07df-40fb-b05d-5063caf8dcc3.png">

**Comment by chrifro** [comment]
- [x] remove "Exchange ideas and knowledge with DevX leaders" +CTA section. It's being replaced with the form

**Comment by nisarhassan12** [comment]
>  the hover effect for the CTA button is missing. It should have a 5px stroke on hover

@chrifro the stroke there will have the same issue as the cards for now it is the same as the cards https://github.com/gitpod-io/devx-community/pull/81
